// Generated by scripts/pin-ffmpeg.mjs — do not edit by hand.
//
// FFmpeg binaries built by https://github.com/BtbN/FFmpeg-Builds under the LGPL. The
// extension never redistributes them; it downloads them from the upstream
// release on the user's own machine, after the user asks for it.

export type ManagedFfmpegArch = 'x64' | 'arm64';

export interface ManagedFfmpegAsset {
	/** Node's `process.arch` value this asset serves. */
	arch: ManagedFfmpegArch;
	archiveName: string;
	url: string;
	/** SHA-256 of the archive, verified before anything is extracted. */
	sha256: string;
	sizeBytes: number;
	/**
	 * Paths inside the archive of the two executables the extension runs. Both are
	 * extracted into one directory because ffprobe is located relative to ffmpeg.
	 */
	entries: { ffmpeg: string; ffprobe: string };
}

/** Dated release tag; `latest` is unusable because its assets are rewritten in place. */
export const MANAGED_FFMPEG_TAG = 'autobuild-2026-08-13-17-03';

/** FFmpeg release branch the pinned build tracks. */
export const MANAGED_FFMPEG_BRANCH = '8.1';

export const MANAGED_FFMPEG_LICENSE_URL =
	'https://github.com/BtbN/FFmpeg-Builds#license';

export const MANAGED_FFMPEG_ASSETS: readonly ManagedFfmpegAsset[] = [
	{
		arch: 'x64',
		archiveName: 'ffmpeg-n8.1.2-34-g9b6c8969e0-linux64-lgpl-8.1.tar.xz',
		url: 'https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-08-13-17-03/ffmpeg-n8.1.2-34-g9b6c8969e0-linux64-lgpl-8.1.tar.xz',
		sha256: '78ecc10fe4b6f97d1125f00dba9a3e2f24d8314c0e7fa592233bfd4adede9fd7',
		sizeBytes: 112453296,
		entries: {
			ffmpeg: 'ffmpeg-n8.1.2-34-g9b6c8969e0-linux64-lgpl-8.1/bin/ffmpeg',
			ffprobe: 'ffmpeg-n8.1.2-34-g9b6c8969e0-linux64-lgpl-8.1/bin/ffprobe',
		},
	},
	{
		arch: 'arm64',
		archiveName: 'ffmpeg-n8.1.2-34-g9b6c8969e0-linuxarm64-lgpl-8.1.tar.xz',
		url: 'https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-08-13-17-03/ffmpeg-n8.1.2-34-g9b6c8969e0-linuxarm64-lgpl-8.1.tar.xz',
		sha256: '643d03144dd9720e1558e0914db7592f08f74904b5ca48c9482cb13a1c01416c',
		sizeBytes: 97181440,
		entries: {
			ffmpeg: 'ffmpeg-n8.1.2-34-g9b6c8969e0-linuxarm64-lgpl-8.1/bin/ffmpeg',
			ffprobe: 'ffmpeg-n8.1.2-34-g9b6c8969e0-linuxarm64-lgpl-8.1/bin/ffprobe',
		},
	},
];

/**
 * The release's own checksum manifest. It is small, lives behind the same
 * redirect chain as the archives, and is pinned here purely so tests can
 * exercise the download-and-verify path without pulling ~100 MB.
 */
export const MANAGED_FFMPEG_PROBE_ASSET = {
	url: 'https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-08-13-17-03/checksums.sha256',
	sha256: '3af50b24b63be5757249815d9b1ee17f243ef0e717a4c582eadc21c6fc8fe801',
	sizeBytes: 5728,
};
